bolcom/unFTP

Cargo.lock, build.rs, src/config.rs, src/main.rs
The server now logs the version and git hash it was build from on startup:
The other change is separation of config parsing a bit in preparation for the cloud native logging. Please not this is my first ever Rust pull request so in a sense I was just experimenting and I'd like your feedback please. Feel free to split some hairs, I'll learn from that.
=> Log versions on startup and separate configuration  a bit.

Cargo.lock, Cargo.toml, src/main.rs, src/redislog.rs
This is a POC showing how we can use [CLAP](https://clap.rs) to support both environment variables and command line arguments. 
It does all the things you need (I've converted 2 arguments):
```
(hannes/clap) unFTP $ ./target/debug/unftp --help
unFTP 0.1.1-15-g3919cff
The bol.com unFTP team
When you need to FTP but don't want to
USAGE:
unftp [OPTIONS]
FLAGS:
--help       Prints help information
-V, --version    Prints version information
OPTIONS:
-a, --bind-address <HOST_PORT>
Sets the host and port to listen on for FTP control connections [env: UNFTP_ADDRESS=]  [default:
0.0.0.0:2121]
-h, --fs-home-dir <FILESYSTEM_BACKEND_HOME_DIR>
Sets the home directory for the filesystem back-end [env: UNFTP_HOME=]  [default:
/var/folders/v2/x05v5xq12j58wzm52w9z4l_1cbm0qc/T/]
```
and the code for that …
=> Use clap for command line argument parsing.

Cargo.lock, Cargo.toml, build.rs, src/app.rs, src/args.rs, src/main.rs
This PR allows us to display eloborate version information for the long version
```sh
$ unftp --version
unFTP 0.4.0
- Git version: v0.4.0-1-g487240d
- Built:       Sun, 03 Nov 2019 06:34:31 +0000
- libunftp:    v0.4.2
- Compiler:    rustc 1.38.0 (625451e37 2019-09-23)
- OS/Arch:     macos/x86_64
- Features:    CLOUD_STORAGE, DEFAULT, PAM, REST
- Debug:       true
```
The short  version still gives just the version:
```sh
$ unftp -V
unFTP v0.4.0-1-g487240d
```
Also on startup we'll log the libunftp version:
```
Nov 03 07:39:47.578 INFO Starting unFTP server., sbe-type: filesystem, auth-type: anonymous, home: /Users/hdejager, address: 0.0.0.0:2121, libunftp-version: 0.4.2, version: v0.4.0-1-g487240d
Nov 03 07:39:47.581 INFO Using anonymous authenticator
```
I used the …
=> Display build metadata in --version

Cargo.lock, Cargo.toml, Makefile, build.rs, src/args.rs, src/main.rs, src/redislog.rs
libunftp will soon implement support for the [proxy protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt). See [the libunftp PR](https://github.com/bolcom/libunftp/pull/187). 
This PR adds support for the above-mentioned in unFTP.
=> Added support for proxy protocol mode

Cargo.lock, Cargo.toml, src/main.rs, src/storage.rs
This PR passes unFTP's structured [slog](https://crates.io/search?q=slog) logger to libunftp while cleanup up unFTP's logging dependencies and colourising log output:
=> Configure latest libunftp to use slog

Cargo.lock, Cargo.toml, src/args.rs, src/main.rs
This adds a command line argument to unFTP:
```
--passive-host <HOST>
Tells how unFTP determines the IP that is sent in response to PASV. Can be fixed, a DNS name or determined
from the incoming control connection. Examples: 'from-connection', '127.0.0.1' or 'ftp.myhost.org' [env:
UNFTP_PASSIVE_HOST=]  [default: from-connection]
```
in reponse to [new functionality in libunftp](https://github.com/bolcom/libunftp/issues/221 ). It also addresses the DNS resolve part of the mentioned ticket.
This PR closes #51
=> Support libunftp's Server.passive_host

Cargo.lock, Cargo.toml, src/args.rs, src/main.rs
This adds a new command line option to unFTP that leverages [new functionality in libunftp](https://github.com/bolcom/libunftp/pull/259)
An excerpt from the startup log:
=> Added --ftps-required-on-control-channel option

Cargo.lock, Cargo.toml, src/args.rs, src/main.rs, src/user.rs
This PR adds support for new functionality in `libunftp` whereby TLS may be set as required for data channel connections.
=> Added --ftps-required-on-data-channel option

Cargo.lock, Cargo.toml, crates/redislog/Cargo.toml, crates/redislog/src/lib.rs, src/logging.rs, src/main.rs, src/storage.rs
This MR moves the _redis logger_ to its own sub-crate as a best practice.  It also moves logging related functions from the main module to a `logging` sub module.
Some unrelated formatting also.
=> Moved redislog module to its own sub-crate

Cargo.lock, Cargo.toml, Makefile, alpine-debug.Dockerfile.template, src/args.rs, src/main.rs
Ability to use the new support for GKE workload identity added to libunftp. See: 
- https://github.com/bolcom/libunftp/issues/298
- https://github.com/bolcom/libunftp/pull/303
This PR adds the `--sbe-gcs-service-account` command line option and the `UNFTP_SBE_GCS_SERVICE_ACCOUNT` environment variable option that will, if specified, use the specific service account when doing authentication using 
GKE workload identity. The `--sbe-gcs-key-file` option is no longer required when `--sbe-type` is 'gcs'. Specifying both `--sbe-gcs-key-file` and `--sbe-gcs-service-account` is an error and omitting both wil activate workload identity authentication using the default service account.
=> Draft: Added support for k8s workload identity.

Cargo.lock, Cargo.toml, src/args.rs, src/main.rs
This PR allows the unFTP user to specify the root directory in the bucket where the Cloud Storage Back-end will look for and put its files.
=> Added --sbe-gcs-root argument

Cargo.lock, Cargo.toml, src/auth.rs, src/main.rs, src/storage/choose.rs, src/storage/mod.rs, src/storage/restrict.rs, src/storage/rooter.rs
This builds on github PR #97 to add a configurable optional home
directory per user as requested in issue #85.
The user's home gets specified in a JSON file pointed to by the
`--usr-json-path` argument. The `root` property needs to be set:
```json
[
{
"username": "alice",
"password": "12345678",
"root": "alice"
},
{
"username": "bob",
"password": "secret",
"root": "bob"
}
]
```
At the moment if the `root` is not specified then the user will gain
access to the root of the storage back-end.
This PR also includes some upgrades and other naming refactorings.
=> Implement per-user home directories

Makefile, crates/redislog/src/lib.rs, src/auth.rs, src/infra/pubsub.rs, src/storage/choose.rs
Not all subscribers of a Pub/Sub topic will be interested in all
messages. For instance the unFTP inventory are only interested in Login
events.
Pub/Sub allows one to filter messages coming into a subscription by
using attribute filters. See
https://cloud.google.com/pubsub/docs/filtering
This commit adds the event type to all outgoing messages by populating
an attribute named `eventType` in the pub/sub messages.
=> Include eventType attribute for pub/sub messages

src/main.rs
The instance name and event name for the pub/sub events were hardcoded
to xxx and yyy which makes it obvious to see that the feature was not
100% complete. This commit fixes that. Sorry...
=> Fix oversight in previous release

Cargo.lock, Cargo.toml, Makefile, build.rs, src/domain.rs, src/infra/pubsub.rs, src/main.rs, src/notify.rs
- Added logout event                                                        
- Added username, trace_id and sequence number to events                    
- BREAKING change to login event. It no longer contains the username        
inseide the login object.                                                 
- Now using the new libunftp notify and notify_data APIs instead of the  
delegate authenticator / delegate storage back-end pattern
=> Improve pub/sub integration

Cargo.lock, Cargo.toml
This commit updates Cargo manifest to explicitly utilize the Tokio features that are needed.
Closes #35
=> Remove unneded tokio features

.github/workflows/rust.yml, README.md, docs/server/installation.md
This creates a CI pipeline based on Github actions. It:
1. Checks formatting
2. Runs clippy
3. Runs tests
4. Creates releases builds for various platforms including windows and macos.
=> Add CI based on Github Actions

.github/workflows/rust.yml, src/main.rs
This fixes building on Windows by putting the unix specific signal handling behind a cfg attribute and adding Windows specific handling too.
=> Fix Windows build

.github/workflows/rust.yml, Makefile, RELEASE-CHECKLIST.md
This includes changes to upload all binary images to the release when one is made from the Github UI.
I also updated the version number in the Makefile (for the docker builds) and removed the `release-artifacts` target which is no longer used.
Lastly I updated the release checklist to reflect the new way of working.
=> Upload release artifacts from the pipeline

Cargo.lock, crates/redislog/Cargo.toml
By eliminating a transitive dependency on time-0.1.45.  This should help compilation time, too.
Also, update the hermit-abi dependency. 0.3.1 was yanked for some reason.
=> Fix Rustsec 2020 0071

docs/server/starting.md
Docs page: https://unftp.rs/server/starting. It's about this command
```
unftp \
-v
--root-dir=/home/unftp/data \
--bind-address=0.0.0.0:2121 \
--passive-ports=50000-51000 \
```
If a new user would run the command like this:
1. There's no escaping after `-v`, so the options supplied afterwards won't get picked up 
2. The command won't be executed right away because of the `/` at the end
Both points are fixed in this pr
=> fix: unftp command in docs had incorrect escaping

src/app.rs, src/auth.rs, src/domain/events.rs, src/domain/mod.rs, src/domain/user.rs, src/infra/mod.rs, src/infra/pubsub.rs, src/infra/usrdetail_json.rs, src/main.rs, src/notify.rs, src/storage/choose.rs, src/storage/mod.rs
This is in preparation for adding a REST or HTTP user detail provider. I'm moving code into the `domain` and `infra` modules. The `domain` module contains the traits to be implemented in the infra packages.
=> Move more things to domain and infra packages

Cargo.lock, Cargo.toml, src/args.rs, src/auth.rs, src/domain/user.rs, src/infra/mod.rs, src/infra/userdetail_http.rs, src/infra/usrdetail_json.rs, src/main.rs
This adds functionality to unFTP that allows unFTP to obtain user
detail over HTTP in addition to the already existing JSON file.
It uses the extact same format as the JSON file functionality. The
'usr-http-url' command line arguments activate this feature. You
pass it a base URL, unFTP appends a username to it and performs
a GET request to the URL. The HTTP server should respond with a
200 OK and JSON body containing an array of users which should
at least contain the requested user's details.
Later on we can support diffent HTTP verbs and sending the
username via an HTTP header instead of the URL path or Post
body. For now I'm just keeping it simple.
=> Add HTTP User Detail extension

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, docs/libunftp/README.md, src/args.rs, src/main.rs, src/storage/choose.rs
This PR adds azure blob support with OpenDAL. Currently we are still waiting for `unftp-sbe-opendal` to release, so it's a git dependency for now. Azure blob can be used as an example for future implementation of storages backed by OpenDAL. 
I'm not sure how should we organize the naming (arg, env) for services provided by OpenDAL though. 
Closes #183
=> feat: add azblob storage backend with opendal

docs/server/docker.md
The ROOT_URL was incorrect and should have been UNFTP_ROOT_URL. Has been discussed in this issue: #164
Also adds more passive ports to help avoid issues until #187 is resolved.
=> Website: Fix UNFTP_ROOT_URL in docker docs and add more passive ports

CHANGELOG.md, Cargo.lock, Cargo.toml, Makefile, README.md, crates/googlelog/Cargo.toml, crates/googlelog/src/error.rs, crates/googlelog/src/lib.rs, crates/googlelog/src/logger.rs, crates/googlelog/src/shipper.rs, docs/server/logging.md, src/args.rs, src/logging.rs, src/main.rs
=> feat: Google Logging support

CHANGELOG.md, docs/server/ftps.md, docs/server/starting.md, src/args.rs, src/main.rs
Before, --auth-type had a default option of anonymous. That way unftp doesn't require any arguments to start up. But we figured this is a potential security hazard: Forgetting to set --auth-type, or making a typo like --authtype would be disastrous.
So this is now disabled.
If you do not pass the --auth-type argument, unFTP will refuse to start up.
If you intentionally want to run a passwordless FTP server, you can pass `--auth-type anonymous` explicitly.
=> Auth-type now a mandatory parameter (breaking change)

src/infra/userdetail_http.rs
Related to #190 
Combined with https://github.com/bolcom/libunftp/pull/520 this change will allow using an https url for REST auth.
=> Allow https for user detail

.github/workflows/rust.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, Makefile, packaging/docker/alpine-debug.Dockerfile.ci, packaging/docker/alpine.Dockerfile.ci, packaging/docker/scratch.Dockerfile.ci, src/args.rs, src/infra/pubsub.rs, src/main.rs, src/storage/choose.rs
This enables unFTP to use ISO files for read-only storage by using
the `unftp-sbe-iso` crate. It puts all the functionality behind
a feature flag called `sbe_iso`.
In this commit, it is not made part of the default build but perhaps
its not a bad idea to do that.
I've noticed that the other features like `cloud_storage` isn't properly
gated behind its features but I didn't want to make this commit too big
so leaving it to be fixed afterwards.
We may also want to stardardise our feature naming a bit e.g. features
that enable storage backends may start with `sbe_` e.g. `sbe_gcs`.
Similarly, auth back-ends may be named `auth_xxx` e.g. `auth_pam`. This
should make things a bit more intuitive as the features pile up.
Other seemingly unrelated changes:
- Compile against Rust 1.86.0 (Needed this …
=> Add ISO storage type

CHANGELOG.md, Cargo.toml, README.md, src/args.rs, src/main.rs, src/storage/choose.rs
Fixed the issue where some of these features were not fully behind `cfg` conditionals. For example there was the problem here that even though the `gcs` back-end was disabled, it would show up in the command line arguments and also if you tried to compile with `--no-default-features` you would simply get compiler errors.
Also made the names more consistent:
- Feature `cloud_storage` is now called `sbe_gcs`
- Feature `opendal` is now called `sbe_opendal`
- Feature `azblob` is now called `sbe_azblob`
- Feature `pam_auth` is now called `auth_pam`
- Feature `rest_auth` is now `auth_rest`
- Feature `jsonfile_auth` is now `auth_jsonfile`
I kept the old names for backwards-compatibility for now but perhaps in the future we can remove them in a breaking change.
=> Cleanup features

README.md, docs/server/installation.md
> involving package repositories:
> 
> - AUR
> - FreeBSD Ports
> - Nixpkgs
This takes care of the last bits of and resolves #216.
It can be merged using rebase.
=> Add installation instructions
