bolcom/unFTP

Cargo.lock
Cargo.toml

I've added the full list of authors, updated some dependencies and added some project metadata.

Cargo.toml polishing

---

Cargo.lock
Cargo.toml
src/args.rs
src/main.rs

This adds the '--idle-session-timeout' argument as per #22 
**WIP Because we first need a new release of libunftp before builds will work and before we can merge this.**

#22 Added a command line argument to set the the idle session timeout

---

Cargo.lock
Cargo.toml
src/args.rs
src/main.rs

Support jsonfile authentication

---

Cargo.lock
Cargo.toml
src/main.rs

Change-Id: I140e56c447d8fa4b789b767ca39474325a9076ec

handle errors from RestAuthenticator

---

Cargo.lock
Cargo.toml
src/main.rs

Use tokio 0.2 instead of tokio compat (#32)

---

Cargo.lock
Cargo.toml
README.md
src/args.rs
src/main.rs

Getting ready for the next libunftp release.
This includes the changes back to Rust-TLS

Upgraded to latest libunftp

---

src/main.rs

Prettified logging to the console:
and then redis as well:

Log to the terminal also when logging to Redis (#47)

---

src/main.rs
src/storage.rs

Notices the lines with "module = storage":

Structured logging for storage back-end events

---

src/main.rs

Catch SIG_INT in addition to SIG_TERM.

Also handle SIG_INT

---

src/logging.rs

This MR lets unFTP continues if the Redis logger cannot be initialized to give better uptime.
This then closes https://github.com/bolcom/libunftp/issues/250

Don't panic if the redis logger cannot be initialized

---

Cargo.toml
Makefile
README.md
alpine-debug.Dockerfile.template
alpine.Dockerfile.template
build.rs
gnubuilder.Dockerfile.template
scratch.Dockerfile.template

Building a dynamic binary with the 'pam' feature included

---

Cargo.lock
Cargo.toml
README.md
rustfmt.toml
src/args.rs
src/main.rs

Add MTLS support

---

CHANGELOG.md
Cargo.lock
Cargo.toml
Makefile
README.md
RELEASE-CHECKLIST.md
src/storage/choose.rs
src/storage/restrict.rs
src/storage/rooter.rs

Use libunftp v0.18.0 and corresponding back-ends

Release unFTP v0.12.11

---

Cargo.lock
Cargo.toml
src/http.rs
src/main.rs

This uses the new functionality in libunftp to implement graceful shutdown for the FTP server and also does so for the HTTP server.

Implement graceful shutdown

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/redislog/src/lib.rs
src/args.rs
src/domain.rs
src/main.rs

See https://github.com/bolcom/libunftp/pull/343

Support the failed logins policy option

---

Cargo.lock
Cargo.toml
src/args.rs
src/main.rs

Failed logins policy default correction

---

Cargo.lock
Cargo.toml
README.md
src/main.rs

I add a `tokio_console` feature that will enable support for [tokio-console](https://github.com/tokio-rs/console). 
Also added some documentation on how to run with this in the README.

Add support for tokio-console

---

src/app.rs
src/auth.rs
src/infra/pubsub.rs
src/logging.rs
src/main.rs

This commit applies the clippy suggestions by running `cargo clippy --fix`

Fix clippy warnings

---

build.rs
rustfmt.toml
src/auth.rs
src/http.rs
src/infra/pubsub.rs
src/infra/workload_identity.rs
src/logging.rs
src/main.rs
src/notify.rs
src/storage/choose.rs
src/storage/restrict.rs
src/storage/rooter.rs

This PR changes the maximum line length to 100 characters. This change aims to improve readability of the code.
In this PR, I removed the max_width of 120 from rustfmt.toml, and ran rustfmt against the main.rs file. This should let rustfmt hit all files.
This change mirrors https://github.com/bolcom/libunftp/pull/431

Change max line length to 100 chars

---

src/main.rs

Until we have a proper support for config-file (and certificate) reload, this will handle a graceful restart.
Resolves #150 for now.

Restart when receiving the HUP signal

---

CHANGELOG.md
Cargo.lock
Cargo.toml
RELEASE-CHECKLIST.md
crates/redislog/Cargo.toml
docs/server/docker.md
docs/server/installation.md
docs/server/pubsub.md

Release unFTP v0.14.4
